const Letters = [
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y",
  "z",
];

const AllBrands = [
  {
    letter: "a",
    brands: [
      "A&E",
      "ACTIV FLORA",
      "API",
      "AUDUBON",
      "Abbott Labs",
      "Accord Healthcare",
      "Acepromazine",
      "Acetylcysteine",
      "Actavis",
      "Adams",
      "Adequan",
      "Advance Aqua Tanks",
      "Advantage",
      "Advantage XD",
      "Advantus",
      "AgriLabs",
      "Air Wick",
      "Akorn",
      "Albon",
      "All Four Paws",
      "All Living Things",
      "Allopurinol",
      "Alpharma",
      "Amlodipine",
      "Amneal Pharmaceuticals",
      "Amoxi-Drop",
      "Amoxi-Tabs",
      "Ampicillin",
      "Amring Pharmaceuticals Inc",
      "Andis",
      "Angels' Eyes",
      "Angry Orange",
      "Ani Mate",
      "Animax",
      "Anipryl",
      "Antirobe",
      "Apexa",
      "Apoquel",
      "Apotex",
      "Applaws",
      "Aqua Clear",
      "Aqua Natural",
      "Aquael",
      "Aquagarden",
      "Aqueon",
      "Arcadia Bird",
      "Arcadia Reptile",
      "Arcadia Trail",
      "Arctic Mice",
      "Ark Naturals",
      "Arm & Hammer",
      "Armarkat",
      "ArthroDynamic Technologies",
      "Ascend Laboratories",
      "Atopica",
      "Atropine",
      "Attitude",
      "Aunt Fannie's",
      "Authority",
    ],
  },
  {
    letter: "b",
    brands: [
      "BARK BARS",
      "BEN & JERRY'S",
      "BIOESQUE",
      "BOXIECAT",
      "Backyard Essentials",
      "Bags on Board",
      "Banamine",
      "Banana Boat",
      "Bark",
      "BarkYard",
      "Baskerville",
      "Bausch + Lomb",
      "Baxter",
      "Bayer Expert Care",
      "Baytril",
      "Beggin' Strips",
      "Benazepril",
      "Beneful",
      "Bergan",
      "Best Buds Brew",
      "Best Friends Mobility",
      "Best Friends by Sheri",
      "Bethanechol",
      "Better Belly",
      "Beyond",
      "Big Mouth",
      "Bil-Jac",
      "Billy and Margot",
      "Bimeda",
      "Biomox",
      "Bissell",
      "Blended Clothing",
      "Blue Buffalo",
      "Blue Buffalo Natural Veterinary Diet",
      "BluePoint Labs",
      "Bocce's Bakery",
      "Bonkers",
      "Booda",
      "Bravecto",
      "Brindle",
      "Brown's",
      "Brutus Broth",
      "Bubble Universe",
      "Bully Beds",
      "Burt's Bees",
      "Busy Bone",
      "biOrb",
    ],
  },
  {
    letter: "c",
    brands: [
      "C&S Products",
      "CANIDAE",
      "CHI",
      "Calm Paws",
      "Camber Pharmaceuticals",
      "Canada Pooch",
      "Capstar",
      "Cardinal Gates",
      "Carefresh",
      "CaribSea",
      "Carlson Pet Products",
      "Carolina Pet",
      "Carprieve",
      "Carprofen",
      "Carprovet",
      "Castor & Pollux",
      "Cat Lures",
      "Cat MX",
      "Cat Mate",
      "Cat Sip",
      "Catalyst",
      "Catit",
      "Catry",
      "Catstages",
      "Cefpodoxime",
      "Centragard",
      "Cerenia",
      "Cesar",
      "Chance & Friends",
      "Charlee Bear",
      "CheckUp",
      "Chicken Soup for the Soul",
      "Chondroprotec",
      "Chorulon",
      "Chuckit!",
      "Ciprofloxacin",
      "CitraVet",
      "Clavamox",
      "Clear-For-Life",
      "Clindamycin",
      "Clintabs",
      "Clomicalm",
      "Clopidogrel",
      "Coastal Pet Products",
      "Cobalt",
      "Collachews",
      "Complete Aquatic Systems",
      "Coralife",
      "Covidien",
      "Crave",
      "Credelio",
      "Current USA",
      "Cyanocobalamin",
      "Cyproheptadine",
      "Cystorelin",
    ],
  },
  {
    letter: "d",
    brands: [
      "DC Comics",
      "DOUXO",
      "Danner",
      "Dava Pharmaceuticals",
      "Dechra Pharmaceuticals",
      "Delectables",
      "Dentley's",
      "Depo-Medrol",
      "Deramaxx",
      "Derma-Vet",
      "Designer Pet Products",
      "Diggs",
      "Digoxin",
      "Dingo",
      "Diphenhydramine",
      "Disney",
      "Dog Gone Smart",
      "Dog Helios",
      "Dog MX",
      "Dog Mate",
      "Dog Rocks",
      "Doggie Dooley",
      "Doggijuana",
      "Doggles",
      "Dogit",
      "Dogswell",
      "Don Roberto",
      "Doxycycline",
      "Dr. Elsey's",
      "Draxxin",
      "Droncit",
      "Drontal",
      "Drymate",
    ],
  },
  {
    letter: "e",
    brands: [
      "E&S Pets",
      "Earth Rated",
      "Earthbath",
      "EasOtic",
      "Ecotrition",
      "Edenbridge Pharmaceuticals",
      "Eggland's Best",
      "Eheim",
      "Elanco",
      "Embark",
      "Emerald Pet",
      "Enalapril",
      "Enrofloxacin",
      "EnteDerm",
      "Entyce",
      "Equidone",
      "Equine Advantage Feed",
      "Equioxx",
      "EstroPLAN",
      "Estrumate",
      "Ethical Products",
      "Eukanuba",
      "Ever Clean",
      "Evercare",
      "Excede",
      "Excenel",
      "Exo-Terra",
      "ExquisiCat",
    ],
  },
  {
    letter: "f",
    brands: [
      "FELIWAY",
      "FIDA",
      "FM Browns",
      "FURminator",
      "Falcon",
      "Famciclovir",
      "Famotidine",
      "Fancy Feast",
      "Featherland Paradise",
      "Felimazole",
      "Feline Pine",
      "Fisher-Price",
      "Flexi",
      "Flovent",
      "Fluker's",
      "Fluval",
      "Fly's Off",
      "Free Spirit",
      "Fresh Pawz",
      "Fresh Step",
      "Freshpet",
      "Friskies",
      "Fritz",
      "Frontline",
      "Full Cheeks",
      "FurZapper",
      "Furosemide",
    ],
  },
  {
    letter: "g",
    brands: [
      "GMASON",
      "Gabapentin",
      "Galliprant",
      "Garmin",
      "GastroGard",
      "GenOne",
      "Geneva",
      "Genius Litter",
      "GentaVed",
      "Gentacalm",
      "Gentamicin",
      "Gentle Giants",
      "Gentocin",
      "Gift Essentials",
      "Glandex",
      "Glenmark Pharmaceuticals",
      "GloFish",
      "Global Source",
      "Great Choice",
      "Greater Wild",
      "Greenbone",
      "Greenies",
      "Grrreen",
      "goDog",
    ],
  },
  {
    letter: "h",
    brands: [
      "HALO",
      "HARI",
      "Halti",
      "Happy Hen Treats",
      "Happy Mutt",
      "Hartz",
      "Healthy Harvest",
      "Heartgard",
      "Hempz",
      "Henry Schein Animal Health",
      "Heritage Farms",
      "Hi-Tech Pharmacal Co",
      "Higgins",
      "High Noon",
      "High Tech Pet",
      "Hikari",
      "Hill's Prescription Diet",
      "Hill's Science Diet",
      "Hillman",
      "Himalayan",
      "Hip Doggie",
      "HomeoPet",
      "Hospira",
      "Hound2O",
      "HyCoat",
      "Hyalovet",
      "Hydroxyzine",
      "Hytryl",
    ],
  },
  {
    letter: "i",
    brands: [
      "Iams",
      "Ichon",
      "Inaba",
      "Incurin",
      "Instachew",
      "Instant Ocean",
      "Instinct",
      "Instincts",
      "Interceptor",
      "Itraconazole",
      "Itrafungol",
      "Iverhart Max",
      "iFetch",
    ],
  },
  {
    letter: "j",
    brands: ["JW Pet", "Jinx", "Jolly Pets", "Joyhound", "JurassiPet"],
  },
  {
    letter: "k",
    brands: [
      "K&H",
      "K-BroVet",
      "K9 Advantix",
      "K9 Sport Sack",
      "KONG",
      "Kalmbach Feeds",
      "Kay Berry",
      "Kaytee",
      "Kenalog",
      "Kent Marine",
      "Kit 'N Kaboodle",
      "Kitty City",
      "Kitty Sift",
      "Kordon",
      "Kruse's Perfection Brand",
      "Kumfy Tailz",
      "Kurgo",
    ],
  },
  {
    letter: "l",
    brands: [
      "La-Z-Boy",
      "Lactulose",
      "Lafeber's",
      "Lannett Company",
      "Lantus",
      "Lazy Dog Cookie Co",
      "Legend",
      "Levetiracetam",
      "Licensed Brand",
      "Lidoject",
      "Lifekey",
      "Liquid-Vet",
      "Litter Genie",
      "LitterMaid",
      "Lixit",
      "Lloyd Laboratories",
      "Loxicom",
      "Lucy & Co.",
      "Lutalyse",
      "Lysodren",
      "Lysol",
    ],
  },
  {
    letter: "m",
    brands: [
      "M-Pets",
      "Mad Cat",
      "Made By Cleo",
      "Made by Nacho",
      "Mag-Float",
      "Majestic Pet",
      "Malaseb",
      "Marboquin",
      "Marina",
      "Marineland",
      "Marquis",
      "Marshall",
      "Marvel",
      "Matterly",
      "Max's Closet",
      "Maxbone",
      "Mazuri",
      "Medrol",
      "Meloxidyl",
      "Meow Mix",
      "Meowijuana",
      "Merck Animal Health",
      "Merrick",
      "Merry & Bright",
      "Metacam",
      "Methio-Form",
      "Methocarbamol",
      "Metoprolol",
      "MetroVac",
      "Miconazole",
      "Miconosol",
      "MicrocynAH",
      "MidWest",
      "Mila International",
      "MilbeGuard",
      "Milbemite",
      "Milk-Bone",
      "Miller's Forge",
      "Minocycline",
      "Miracle Care",
      "Mirataz",
      "Mizner",
      "Mobile Dog Gear",
      "Moist & Meaty",
      "Mometamax",
      "Mometavet",
      "More Birds",
      "Morton",
      "Multimin",
      "Multipet",
      "Muricin",
      "Mylan",
    ],
  },
  {
    letter: "n",
    brands: [
      "NOM NOM",
      "NUTRO",
      "Nala Cat",
      "Nate & Jeremiah",
      "NaturVet",
      "Natural Balance",
      "Naturally Fresh",
      "Nature's Animals",
      "Nature's Miracle",
      "Nature's Ocean",
      "Nature's Protection",
      "Nature's Recipe",
      "Nature's Variety Instinct",
      "Naxcel",
      "Neater Pets",
      "Neo-Predef",
      "Neogen Corporation",
      "Nephron Pharmaceuticals Corporation",
      "Nerf Cat",
      "Nerf Dog",
      "Netflix",
      "New Age Pet",
      "NexGard",
      "NextStar",
      "Nipro Diagnostics",
      "Nite Ize",
      "Nivagen",
      "Normosol-R",
      "North States",
      "Novox",
      "Nuflor",
      "Nulo",
      "Nutramax Laboratories",
      "Nutro Max",
      "Nutro Ultra",
      "Nylabone",
    ],
  },
  {
    letter: "o",
    brands: [
      "OASE",
      "OMG! Surprise",
      "Oasis",
      "Ocean Nutrition",
      "Oculenis",
      "Okocat",
      "Old Mother Hubbard",
      "Omega One",
      "Omega Paw",
      "Omega Plus",
      "Ondansetron",
      "Only Natural Pet",
      "Onsior",
      "Optimmune",
      "OraVet",
      "Orbax",
      "Osphos",
      "Ostimax",
      "Osurnia",
      "Otomax",
      "Outward Hound",
      "OvaMed",
      "Oxbow",
      "Oxytocin",
    ],
  },
  {
    letter: "p",
    brands: [
      "PAIKKA",
      "Pacific Pharmaceuticals Limited",
      "Packed Party",
      "Palladia",
      "PanaKare",
      "Panacur",
      "PancrePlus",
      "Par Pharmaceutical Companies",
      "Paw Pops",
      "Paw Prints",
      "Paw Thaw",
      "PawZ",
      "Pawscout",
      "Pedigree",
      "Pendleton",
      "Penn-Plax",
      "Pennington",
      "Pentosan",
      "Percorten",
      "Perfect Pet",
      "Perrigo",
      "Pet Botanics",
      "Pet Corrector",
      "Pet Dreams",
      "Pet Gear",
      "Pet Genius",
      "Pet Greens",
      "Pet Halloween",
      "Pet Head",
      "Pet Honesty",
      "Pet Life",
      "Pet Qwerks",
      "Pet Wellbeing",
      "Pet Zone",
      "Pet-Pourri",
      "PetAg",
      "PetArmor",
      "PetPals",
      "PetSTEP",
      "PetSafe",
      "PetSmart",
      "PetSmart Charities",
      "Petivity",
      "Petlinks",
      "Petmate",
      "Pets First",
      "Petstages",
      "Phenylbute",
      "Pink Papyrus",
      "Pioneer Pet",
      "Piroxicam",
      "Playology",
      "Polyflex",
      "Polyglycan",
      "PondCare",
      "Pooch Creamery",
      "PoochPad",
      "Pork Chomps",
      "PortablePet",
      "PortoPet",
      "Posatex",
      "Prascend",
      "Precious Cat",
      "Precision Pet",
      "Premier",
      "Presido Pet",
      "Previcox",
      "Prevue Pet Products",
      "Primetime Petz",
      "Primidone",
      "Primor",
      "ProZinc",
      "Profender",
      "Project Hive Pet Company",
      "Pup Cup",
      "Pup-Peroni",
      "Pupford",
      "Puppia",
      "PureBites",
      "Purina",
      "Purina Cat Chow",
      "Purina Dog Chow",
      "Purina Kitten Chow",
      "Purina ONE",
      "Purina Pro Plan",
      "Purina Pro Plan Veterinary Diets",
      "Purina Puppy Chow",
      "Python Products",
    ],
  },
  {
    letter: "q",
    brands: ["Qualitest Pharmaceuticals", "Quartermaster", "Quellin"],
  },
  {
    letter: "r",
    brands: [
      "REALTREE",
      "ROAM",
      "Rachael Ray Nutrish",
      "Ranbaxy Pharmaceuticals",
      "ReBalance",
      "Reconcile",
      "Redbarn",
      "Regu-Mate",
      "RenaKare",
      "RenaPlus",
      "Rep-Cal",
      "Repashy",
      "Resolve",
      "Reveal",
      "Revolt",
      "Revolution",
      "Richell",
      "Right Choice",
      "Rilexine",
      "Rimadyl",
      "Rocco & Roxie",
      "Rosewood",
      "Roxane Laboratories Inc",
      "Royal Canin",
      "Royal Canin Veterinary Diet",
      "Rubies",
      "Rufus & Coco",
      "Rustic Farmhouse",
    ],
  },
  {
    letter: "s",
    brands: [
      "SMZ",
      "Salix",
      "San Francisco Bay",
      "Sandoz",
      "Sassy Woof",
      "Sauder",
      "Science Selective",
      "Scoop Away",
      "Scoop Free",
      "Seachem",
      "Sealy",
      "Selarid",
      "Selegiline",
      "Semintra",
      "Senergy",
      "Sentinel",
      "Sentry",
      "Sera",
      "Seresto",
      "Sergeants",
      "Shameless Pets",
      "Sheba",
      "Sherpa",
      "Show String",
      "Silark",
      "Sildenafil",
      "Sileo",
      "SiliDog",
      "Silver Honey",
      "Silver Sulfadiazine",
      "Simparica",
      "Simparica Trio",
      "Simple Green",
      "Simple Solution",
      "Simplicef",
      "Simply Nourish",
      "Skout's Honor",
      "Smart Pet Love",
      "SmartBones",
      "SmartCat",
      "Snoop Doggie Doggs",
      "Snoozer",
      "Snoozzy",
      "Solid Gold",
      "Songbird",
      "Sotalol",
      "Spectramast",
      "Spironolactone",
      "Sport Pet",
      "SportDOG",
      "Squirrel-X",
      "Starmark",
      "Stewart",
      "SucroMate",
      "Sun Seed",
      "Sunbeam",
      "Super Pet",
      "Surolan",
      "Sustainably Yours",
      "Sweet Comb",
      "Sweet Country",
      "Sweet Pickles",
      "Sweet n Salty",
      "Swheat Scoop",
      "Synotic Otic",
    ],
  },
  {
    letter: "t",
    brands: [
      "T8 Keto",
      "TUFFY",
      "TagWorks",
      "Taro Pharmaceutical Industries",
      "Temaril-P",
      "Temptations",
      "Terbinafine",
      "Tetra",
      "Teva",
      "The Bug Company",
      "The Cat Ladies",
      "The Lazy Dog Cookie Co.",
      "The Missing Link",
      "TheGreenPetShop",
      "Thiamine",
      "Thrills & Chills",
      "Thrive",
      "ThunderShirt",
      "ThunderWunders",
      "Thyro-L",
      "Thyro-Tabs",
      "Thyrovet",
      "Tidy Cats",
      "Tiki Cat",
      "Tiki Dog",
      "Top Fin",
      "Top Paw",
      "Touchdog",
      "Tresaderm",
      "Tri-Heart",
      "Tribute",
      "Trifexis",
      "Trixie",
      "TropiClean",
      "True Earth",
      "Two By Two",
      "Tylan",
      "Tylosin",
      "Tylovet",
    ],
  },
  {
    letter: "u",
    brands: [
      "Ulticare",
      "Under the Weather",
      "Unichem Laboratories",
      "Uniprim",
      "Upsher-Smith Laboratories",
      "Ursodiol",
    ],
  },
  {
    letter: "v",
    brands: [
      "Value Beds",
      "Vedco",
      "Ventipulmin",
      "Ventolin",
      "Veraflox",
      "Vet Brand International",
      "Vet Worthy",
      "Vet's Best",
      "VetIQ",
      "VetOne",
      "VetPen",
      "Vetadryl",
      "Vetality",
      "Vetameg",
      "Vetericyn",
      "Vetmedin",
      "Vetoryl",
      "Vetprofen",
      "Vetropolycin",
      "Vetsulin",
      "Viokase-V",
      "Virbac",
      "Virbantel",
      "Vista Pharmaceuticals",
      "Vitakraft",
      "Vittles Vault",
      "Viva La Kitty",
    ],
  },
  {
    letter: "w",
    brands: [
      "WACKYwalk'r",
      "WILD BIRD LOVERS",
      "WOODLINK",
      "Wahl",
      "Ware",
      "Watson Pharmaceuticals",
      "Wellness",
      "Weruva",
      "Wesco Pet",
      "West-Ward",
      "Wet Ones",
      "Wham-O",
      "Whimzees",
      "Whisker City",
      "Whole Earth Farms",
      "Whole Life Pet",
      "Wiggles &amp; Wags",
      "Wigzi",
      "World's Best",
      "Wyze",
    ],
  },

  {
    letter: "x",
    brands: ["XPOWER"],
  },

  {
    letter: "y",
    brands: ["YIP", "YackyCharms", "YoPup", "You Are Loved", "Yummy Combs"],
  },

  {
    letter: "z",
    brands: [
      "Zee Dog",
      "ZenPet",
      "Zeniquin",
      "Zesty Paws",
      "Zilla",
      "Zoetis",
      "Zonisamide",
      "Zoo Med",
      "ZuPreem",
      "Zuke's",
      "Zycortal",
      "Zydus Pharmaceuticals",
      "Zymox",
    ],
  },
];

export { Letters, AllBrands };
