const FIELDS = [
  {
    label: "First Name",
    placeholder: "Enter first name",
    name: "firstname",
    type: "text",
    id: "fname",
  },
  {
    label: "Last Name",
    placeholder: "Enter last name",
    name: "lastname",
    type: "text",
    id: "lname",
  },
  {
    label: "Email",
    placeholder: "Enter email address",
    name: "email",
    type: "email",
    id: "email",
  },
  {
    label: "Phone Number",
    placeholder: "Enter phone number",
    name: "phonenumber",
    type: "text",
    id: "pnum",
  },
  {
    label: "Address",
    placeholder: "Enter Address",
    name: "address",
    type: "text",
    id: "address",
  },
  {
    label: "Birth Date",
    placeholder: "Enter birth date",
    name: "birthDate",
    type: "date",
    id: "bd",
  },
  {
    label: "Social Security Number",
    placeholder: "Enter social security number",
    name: "ssn",
    type: "password",
    id: "ss",
  },
  {
    label: "Employee Number",
    placeholder: "Enter employee number",
    name: "empNum",
    type: "text",
    id: "en",
  },
  {
    label: "Office Number",
    placeholder: "Enter office number",
    name: "office",
    type: "text",
    id: "office",
  },
  {
    label: "Position",
    placeholder: "Enter position",
    name: "position",
    type: "text",
    id: "position",
  },
  {
    label: "Hourly Rate",
    placeholder: "Enter hourly rate",
    name: "hourlyRate",
    type: "text",
    id: "hr",
  },
  {
    label: "Hire Date",
    placeholder: "Enter hire date",
    name: "hireDate",
    type: "date",
    id: "hd",
  },
];

export default FIELDS;
